### ISSUE TITLE
Panicks when losing network connectivity, or Telegram returns errors

### ISSUE THREAD

**Issue by Neurrone** [telegram-rs/telegram-bot#130]
Hi,

While developing my bot, I've been running it on my laptop for a few days. It sometimes aborts with the following panick, most likely when I am momentarily disconnected from the internet:

```Rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Hyper(Error(Connect, Os { code: 10051, kind: Other, message: "A socket operation was attempted to an unreachable network." })), State { next_error: None, backtrace: None })', src\libcore\result.rs:1051:5
```

I've since hosted it on a Linode, so this shouldn't happen again. But it would still be good to handle this gracefully to resume receiving updates once connectivity is restored, and not crash.

**Comment by Neurrone** [comment]
Another more serious instance when this occurs is when the Telegram API returns a `500`, which also causes panicks. I'll take a stab at submitting a PR for this.

Stack trace:

```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Raw(TelegramError { description: "Internal server error: restart", parameters: None }), State { next_error: None, backtrace: Some(stack backtrace:
   0: error_chain::make_backtrace::h2c23a5b378897322 (0x790caa)
   1: <error_chain::State as core::default::Default>::default::h646253ac16ff9717 (0x790d36)
   2: <telegram_bot_raw::requests::_base::errors::Error as error_chain::ChainedError>::from_kind::h864942df1d34c3fc (0x742b95)
   3: telegram_bot_raw::requests::_base::response_types::json::<impl telegram_bot_raw::requests::_base::_base::ResponseType for Resp>::deserialize::h7d8a6a1b561f1524 (0x493e73)
   4: futures::future::chain::Chain<A,B,C>::poll::h734f02c438dbb98d (0x4d0d38)
   5: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h4f318d23b08d149a (0x4b3579)
   6: <futures::future::select::Select<A,B> as futures::future::Future>::poll::h361070b9c7986920 (0x524dd9)
   7: <futures::future::map::Map<A,F> as futures::future::Future>::poll::hfef9d5db50776b26 (0x51a15e)
   8: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h616662d89dc7e6df (0x527111)
   9: <telegram_bot::stream::UpdatesStream as futures::stream::Stream>::poll::hc744c5d2cae6d247 (0x4b3ac4)
  10: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::h7e49b24f6db883b5 (0x43bf46)
  11: futures::task_impl::std::set::hc014f83a3e35b873 (0x434b64)
  12: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::h932672329333ccce (0x4580a1)
  13: futures::task_impl::std::set::h187cb95b5a7a2cdf (0x4348e4)
  14: std::thread::local::LocalKey<T>::with::h6816068c6a6af82d (0x433a04)
  15: tokio_current_thread::Entered<P>::block_on::h26bfbb46562e904f (0x42f8cb)
  16: std::thread::local::LocalKey<T>::with::h8c1649a73bb74277 (0x433c1d)
  17: std::thread::local::LocalKey<T>::with::hf31be9d7f5de09e9 (0x434329)
  18: std::thread::local::LocalKey<T>::with::hea75958e82e0784b (0x43403f)
  19: scoped_tls::ScopedKey<T>::set::hf7a68e5af19feae8 (0x434d9a)
  20: food_ordering_bot::main::h2a8c47155550af42 (0x46300b)
  21: std::rt::lang_start::{{closure}}::h045b16e85b75d53e (0x4594a3)
  22: std::rt::lang_start_internal::{{closure}}::h52e30c7908fe68b7 (0x7b6e03)
             at src/libstd/rt.rs:49
      std::panicking::try::do_call::h2ea8cd7434cffd4d
             at src/libstd/panicking.rs:293
  23: __rust_maybe_catch_panic (0x7ba7ba)
             at src/libpanic_unwind/lib.rs:85
  24: std::panicking::try::h549742e035b8a472 (0x7b786b)
             at src/libstd/panicking.rs:272
      std::panic::catch_unwind::h406d801f678c0df0
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal::h4b30ec1a8a6b305f
             at src/libstd/rt.rs:48
  25: main (0x463732)) })', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: food_ordering_bot::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  14: main
```

**Comment by gugahoa** [comment]
If you need some pointers, feel free to comment here and I'll try to answer in time

**Comment by Neurrone** [comment]
Would appreciate some code pointers; this is also the first time I'm working with futures. 

The second error that I posted appears to be deserialization breaking, and the closest I've gotten to the source of that was on `raw/src/types/message.rs` line 350.

Not sure about how to resolve the first error.

**Comment by gugahoa** [comment]
I would start with `Api::send` and similar functions, which are used to communicate with the Telegram Bot API. From there you can dig more on functions called to see if you can find something interesting. I would algo grep the codebase for unwraps and see if they're on functions that could be on the `Api::send` call path

**Comment by Neurrone** [comment]
I've trakced this down to the following line in my bot:

```
core.run(future).unwrap()
```

This will fail every time some error is encountered, e.g disconnection from the network. 

I tried resolving this error by re-running `core.run` in a loop if an error is encountered, but get a complain about the future being already moved in the previous iteration of the loop. Don't know enough about how tokio works to debug it :(

**Comment by Neurrone** [comment]
I have a workaround for the issue, am not sure if this is the best solution.

The `Stream` trait has 2 associated types: the `Item` returned by the stream, and the `Error` type. The `for_each` method from the `Stream` trait only invokes the provided closure for `Item` (in our case `Update` values). When there's an error, the whole future errors.

I'm preventing the `Stream` from ever returning an error by returning an Update with the undocumented `UpdateKind::Error` variant.

```
--- a/src/main.rs
+++ b/src/main.rs
@@ -21,7 +21,19 @@ fn main() {
     let mut bot = bot::Bot::new();

     // Fetch new updates via long poll method
-    let future = api.stream().for_each(|update| {
+    let future = api.stream()
+    .inspect_err(|err| eprintln!("{:?}", err))
+    // map Err to Ok variant
+    // this is terrible, but I'm resorting to this to prevent errors from crashing the bot
+    // TODO: figure out if there's a better way of preventing errors from panicking
+    .then(|r| {
+        match r {
+            Ok(_) => r,
+            // it doesn't matter if we use an id of 1, since nothing uses it. This is terrible though :(
+            Err(e) => Ok(Update { id: 1, kind: UpdateKind::Error(e.description().to_string())})
+        }
+    })
+    .for_each(|update| {
         // If the received update contains a new message...
         if let UpdateKind::Message(message) = update.kind {
             if let MessageKind::Text { ref data, .. } = message.kind {
@@ -78,5 +90,6 @@ For feature requests, bug reports and source: https://github.com/Neurrone/food-o
         Ok(())
     });

+    // this should never panick, since we prevent the stream's future from returning an error
     core.run(future).unwrap();
 }
```

**Comment by gugahoa** [comment]
After reading through this issue again, it seems that the library is working as intended, surfacing the error to the user. The solution, as can be seen in the fix, is to handle the error when calling the stream.

**Comment by Neurrone** [comment]
The solution I have above still feels hackish, because it works by using an undocumented variant just to prevent errors from ever surfacing, to halt the future's execution. Not sure if I've missed a better way of doing this.

**Comment by gugahoa** [comment]
@Neurrone  You could use https://docs.rs/futures/0.2.0/futures/stream/trait.StreamExt.html#method.or_else to handle the error while not halting the stream, or https://docs.rs/futures/0.2.0/futures/stream/trait.StreamExt.html#method.recover
